language: php

php:
   - 5.5
   - 5.4

before_script:
   - pear channel-discover pear.phpunit.de
   - pear install -a -f --alldeps phpunit/PHPUnit

install:
   - composer install
   - composer dump-autoload

script: phpunit
