notifications:
  email: false

language: php

php:
  - 5.6
  - 5.5
  - 5.4
  - hhvm

before_script:
  - "composer install --dev --prefer-source --no-interaction"

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml.dist

after_script:
  - php vendor/bin/coveralls -v --exclude-no-stmt

cache:
  directories:
    - vendor 